src/base58.cpp
src/chain.h
src/chainparams.cpp
src/chainparams.h
src/miner.cpp
src/primitives/block.h
src/rpc/blockchain.cpp
src/rpc/misc.cpp
src/txdb.cpp
src/util.cpp
src/util.h
src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp

Add unique prefix to address (random for now). Extended address generated so that payee can extract the appropriate information for the transaction, while the pay to address in the transaction is the encoding of tweaked pub key.
Add contract hash to block header and the genesis block.

WP1/2 Complete address and contract

---

qa/rpc-tests/confidential_transactions.py
qa/rpc-tests/listsinceblock.py
qa/rpc-tests/rawtransactions.py
qa/rpc-tests/receivedby.py
qa/rpc-tests/test_framework/util.py
qa/rpc-tests/wallet.py
qa/rpc-tests/zapwallettxes.py
src/assetsdir.cpp
src/chainparams.cpp
src/chainparamsbase.cpp
src/chainparamsbase.h
src/test/assetsdir_tests.cpp
src/util.cpp
src/wallet/rpcwallet.cpp

@tomt1664 
I've so far replaced BTC with CBT as the host coin and changed the creation time to generate a custom genesis block.
There's currently an initial issuance of 21Mil CBT which is OP_TRUE (available to any wallet). I guess we'll need to change this in such a way that only the central node can spend these, so probably signing these with a private key which will then be imported to the main node wallet?

Demo - Customize Ocean

---

src/wallet/rpcdump.cpp
src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp

Make confidential addresses optional when issuing assets
Make wallet use the genesis contract hash when the chain is not active. It was previously using the local contract file, which might not be available/up to date in client wallets.

Some fixes for CT and wallet 

---

src/init.cpp
src/validation.cpp
src/validation.h

added configuration option to block asset issuance transactions to mempool
-issuanceblock=1 will prevent a transaction that has any asset issuance transactions from entering the mempool. 
This can be used to stop asset issuance transactions created by public wallets from reaching signing nodes (so only authorised issuance nodes connected directly to the signing nodes can issue assets).

Issuance block

---

qa/pull-tester/rpc-tests.py
qa/rpc-tests/confidential_transactions.py
qa/rpc-tests/wallet.py
src/bench/coin_selection.cpp
src/bench/mempool_eviction.cpp
src/miner.cpp
src/miner.h
src/policy/policy.cpp
src/rpc/blockchain.cpp
src/test/test_bitcoin.cpp
src/test/test_bitcoin.h
src/txmempool.cpp
src/txmempool.h
src/validation.cpp
src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp
src/wallet/wallet.h

Mempool entries include fee asset information
Coinbase includes fees on multiple asset ids
Sendtransaction to pay fees on the asset send, sendmany to include an option for fee asset (else first asset chosen)
Issue/reissue/destroy to still use the policy asset
Re-enable confidential_transactions unit test in order to test issuance related transactions

Ocean fee changes

---

qa/rpc-tests/wallet.py
src/wallet/rpcwallet.cpp

A new RPC that generates an unsigned raw issuance transaction based on supplied addresses and amounts, and the input outpoint containing policyAsset to spend from (this is needed to generate the asset and token IDs). 
The raw transaction can then be signed directly with signrawtransaction.

new raw issuance rpc

---

qa/pull-tester/rpc-tests.py
qa/rpc-tests/raw_issuance.py
qa/rpc-tests/wallet.py
src/policy/policy.cpp
src/primitives/transaction.cpp
src/validation.cpp
src/wallet/rpcwallet.cpp

With -issuanceblock enabled, policy is now to accept new issuance transactions only if the single input is of the type policyAsset. New QA test to test that policyAsset issuances pass and issued asset input issuances are blocked. 
Issuance transactions are accepted as policy with no fee outputs. 
createrawissuance RPC modified to create issuances with no fee output
Address whitelist policy check allows through issuance transactions

policy changes to restrict issuance and allow no fees

---

src/rpc/rawtransaction.cpp

HexStr(entropy) displaying incorrect value. Changed to entropy.GetHex().

txtojson issuance entropy bug

---

qa/rpc-tests/asset_stats.py
src/policy/policy.cpp
src/policy/policy.h
src/validation.cpp
src/wallet/rpcwallet.cpp

A new RPC to create raw transactions sending a single input to a null (OP_RETURN) output. 
The burning of tokens should not require a transaction fee, so a new exception is added to the mempool acceptance fee check.

burn asset rpc and fee execption

---

qa/pull-tester/rpc-tests.py
qa/rpc-tests/mempool_accept.py
src/rpc/rawtransaction.cpp
src/validation.cpp
src/validation.h

New RPC call to enable the validity of raw transactions to determined (i.e. they have valid inputs/signatures etc) without actually sending the tx to the mempool. 
Is based on the testmempoolaccept RPC added to Bitcoin 0.17 but not in Elements yet.

added testmempoolaccept RPC

---

qa/rpc-tests/asset_stats.py
src/init.cpp
src/policy/policy.cpp
src/policy/policy.h
src/rpc/blockchain.cpp
src/test/blind_tests.cpp
src/validation.cpp
src/validation.h
src/wallet/wallet.cpp

Two new in-memory lists added to enable the automatic reissuance (inflation) of assets: assetEntropyMap and freezeHistMap. 
assetEntropyMap stores the entropy and reissuance token for each asset. This list is updated each time a new asset is issued. These values are required to create a raw reissuance transaction (for the original reissueasset RPC, these are found from the issuing wallet, however for a multisig reissuance there is no way to determine them from the asset ID alone). 
freezeHistMap keeps a list of outputs that are tagged as frozen (and the blockheight when they are confirmed) and then records if these outputs are spent (and the spending tx block height). This is required to pause and backdate inflation payments if a redemption is canceled/failed. 
The assetEntropyMap is then …

Freezetrack

---

qa/rpc-tests/requests.py
src/Makefile.am
src/Makefile.test.include
src/init.cpp
src/policy/policy.cpp
src/policy/policy.h
src/policy/requestlist.cpp
src/policy/requestlist.h
src/pubkey.h
src/request.h
src/rpc/blockchain.cpp
src/rpc/misc.cpp
src/rpc/rawtransaction.cpp
src/script/script.cpp
src/script/sign.cpp
src/script/standard.cpp
src/script/standard.h
src/test/script_standard_tests.cpp
src/validation.cpp
src/validation.h

- ported standard refactoring from bitcoin
https://github.com/bitcoin/bitcoin/pull/13194
- ported scripts_standard test
https://github.com/bitcoin/bitcoin/blob/master/src/test/script_standard_tests.cpp
I've commented stuff to do with witness refactoring and also bare multisig not being standard in bitcoin.
- new tx type TX_LOCKED_MULTISIG (#104)
- Solver handling for TX_LOCKED_MULTISIG (#104)
- sign handling for TX_LOCKED_MULTISIG (#104)
- end to end `requests.py` test: create raw request, fetch requests, spend previously locked request on expiry
- add Request class and FromSolutions constructor
- added Request list and add/remove/update on init and connect block

Guardnode: CLTV multisig transaction Solver/Signing and Request changes

---

src/policy/policy.cpp

The 'zero address' (P2PKH) is used as a flag for a redemption transaction - it does not need to be checked that it is on the whitelist (but the other outputs in the same transaction do). 
I will add a test for this.

added zero address exception to iswhitelisted

---

qa/rpc-tests/onboard.py
qa/rpc-tests/policytransactions.py
qa/rpc-tests/raw_issuance.py
qa/rpc-tests/request-auction.py
qa/rpc-tests/request-bids.py
qa/rpc-tests/requests.py
qa/rpc-tests/wallet.py
src/assetsdir.cpp
src/chainparams.cpp
src/chainparams.h
src/consensus/params.h
src/init.cpp
src/policy/policy.cpp
src/policy/policy.h
src/request.h
src/rpc/blockchain.cpp
src/rpc/rawtransaction.cpp
src/test/test_bitcoin.cpp
src/validation.cpp
src/wallet/rpcwallet.cpp

I have made significant changes to the getrawtransaction rpc. A new assetlabel field has been added for all policy assets (WHITELIST, BURNLIST, etc). Additionally, an extra field ("request" or "bid") has been added to outputs of lockedmultisig type. These fields parse and store data for transactions that carry information relating to the auction. I have implemented issuanceAsset which has replaced policyAsset in some locations. Changes have been made to QA tests to accommodate these features.
Fixes #117

HF: Several changes to policy assets and getrawtransaction rpc

---

src/validation.cpp

Title describes all. Comparing two CTxDestinations could result in weirdness as the variant types each have different behaviour for overloaded comparison operator.

Minor change to safety checks for comparing multisig tweaked id's

---

qa/rpc-tests/onboardmanual.py
src/policy/kycfile.cpp
src/policy/whitelist.cpp
src/policy/whitelist.h
src/script/registeraddressscript.cpp

The transaction now includes the number of pub keys that each Multisig has.
A couple of extra python tests for it were added.

Fixed an issue with multisig whitelisting

---

qa/rpc-tests/replace-by-fee.py
src/consensus/consensus.h

Coinbase txs can be spent after 2 confirmations - this is required to enable the redemption of the final asset in the inflation model.

HARD FORK: changed coinbase maturity to 2 blocks

---

qa/pull-tester/rpc-tests.py
qa/rpc-tests/contractintx.py
qa/rpc-tests/onboard_cit.py
qa/rpc-tests/signcontract.py
src/chainparams.cpp
src/chainparams.h
src/init.cpp
src/policy/kycfile.cpp
src/policy/policy.cpp
src/policy/policy.h
src/policy/whitelist.cpp
src/script/registeraddressscript.cpp
src/validation.cpp
src/validation.h
src/wallet/rpcdump.cpp
src/wallet/wallet.cpp

Config option to include the contract hash in transactions instead of via tweaking. 
Onboarding and whitelisting remains the same, however if contractintx=1, the supplied public keys must correspond the the address without tweaking. 
The wallet does not tweak keys for onboarding. 
sendtoaddress adds the contract hash as a zero value OP_RETURN to all transactions. 
All non-policy and non-burn transactions are checked that they include the contract hash as an OP_RETURN output before accepting to the mempool.

Signcontract

---

src/init.cpp

The lack of `(default: %u)"` was crashing `oceand`. Lovely bitcoin codebase.

Fix help message

---

qa/rpc-tests/splittransactions.py

The test seems to be failing 5% of the time. On that occasion "sendanytoaddress" creates 2 transactions from which only one is successfully broadcast.
The rpc seems to be a bit unstable but I haven't managed to find any issues and it takes ages to test because a very large number of assets/outputs is required to create such a big transaction. Given how little we are planning to use this and the fact that the error here is not that critical, I might disable the test if it fails again.

Fix split tx test

---

src/chainparams.cpp

Disable default checks that slow down syncing. These include checkblockindex and ckeckmempool and should only be enabled periodically or on demand.
Fix #246

Syncing speed issue

---

qa/rpc-tests/onboard_cit.py

Generate some extra blocks in the onboard_cit test to allow the whitelist state to sync up.

Extra blocks generated in onboard_cit.py

---

qa/pull-tester/rpc-tests.py
qa/rpc-tests/onboardmanual_cit.py
qa/rpc-tests/recoverencryptionkeys.py
src/init.cpp
src/policy/kycfile.cpp
src/policy/whitelist.cpp
src/policy/whitelist.h
src/policy/whitelistEncrypted.cpp
src/rpc/client.cpp
src/validation.cpp
src/validation.h
src/wallet/rpcwallet.cpp
src/wallet/rpcwallet.h
src/wallet/wallet.cpp
src/wallet/wallet.h
src/wallet/walletdb.cpp
src/wallet/walletdb.h

- RPCs for recovery of encryption keys: recoverencryptionkey and recoverkyckeys. These can be used to generate the encryption keys when the wallet is loaded from an earlier state or restored from seed.
- Do not automatically try and recover encryption keys for every wallet (sync_whitelist_wallet removed from whitelist.cpp). The above RPCs can be used instead, if needed.
- Store the encryption keys HD chain independently. Seperate child counters for main and encryption HD wallet paths.

Recover keys

---

qa/rpc-tests/onboard.py
qa/rpc-tests/onboard_cit.py
qa/rpc-tests/onboardencrypted.py
src/test/getarg_tests.cpp
src/test/util_tests.cpp
src/util.cpp
src/util.h

https://github.com/commerceblock/ocean/issues/261

check input args

---

qa/rpc-tests/onboard_cit.py
qa/rpc-tests/onboardmanual_cit.py
src/util.cpp
src/wallet/rpcwallet.cpp

When generating whitelisting transaction, the min number of confirmations to spend outputs is set to 1

Min depth for usable whitelist asset = 1

---

qa/rpc-tests/sendany.py
src/policy/policy.cpp
src/rpc/client.cpp
src/wallet/rpcwallet.cpp

Allow one extra OP_RETURN output in transactions in order to accommodate the sendanytoaddress RPC metadata.

Increase spam tolerance
