commerceblock/ocean

src/rpc/protocol.h
src/wallet/rpcdump.cpp
src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp
src/wallet/walletdb.h

Dump derived keys
Validate keys

WP3 Wallet

---

qa/pull-tester/rpc-tests.py
qa/rpc-tests/unconfidential_transactions.py
src/blind.cpp
src/primitives/transaction.cpp
src/primitives/transaction.h
src/rpc/rawtransaction.cpp
src/validation.cpp
src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp

Fix reissuance bug by using an arbitrary assetblindingnonce for unblinded reissuances
Replicate confidential_transactions unit test for unblinded transactions

Reissuance fix

---

src/chainparams.cpp

use different prevout for each issuance #70

Fix genesis issuance for wallet

---

qa/rpc-tests/createrawrequesttx.py
qa/rpc-tests/redemption.py
src/rpc/rawtransaction.cpp
src/validation.cpp

solve problem

---

src/chainparams.cpp
src/util.cpp
src/util.h

Fix broken Help Message

---

qa/rpc-tests/policytransactions.py
qa/rpc-tests/redemption.py
qa/rpc-tests/validBurn.py
qa/rpc-tests/whitelisting.py
src/policy/policy.cpp
src/policy/policy.h
src/script/sign.cpp
src/script/standard.cpp
src/validation.cpp

Made some changes to the burn/freeze policy logic. 
Redemption transactions don't need fees. 
Fixed bug in IsPolicy()
Changes to some tests.

Policyfixes

---

qa/rpc-tests/onboard.py
src/policy/policy.cpp
src/policy/policy.h
src/policy/whitelist.cpp
src/validation.cpp
src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp

Zero fees for poilcy assets when using createtransaction. Onboarding must be done with whitelistAsset.

Whitelist asset registeraddress

---

src/blind.cpp
src/script/sigcache.cpp
src/test/blind_tests.cpp

Bug fixes from the following Elements project pull requests: 491, 509, 489, 514.

Elements bugfixes

---

qa/rpc-tests/redemption.py
qa/rpc-tests/validBurn.py
src/validation.cpp

testmempoolaccept now by-passes the whitelist, freezelist and burnlist checks.

test_accept excluded from policy checks

---

src/init.cpp
src/util.cpp
src/util.h

Allow debug printing to both console and debug.log

---

qa/rpc-tests/onboard.py
qa/rpc-tests/requests.py
src/request.h
src/rpc/blockchain.cpp
src/test/policy_tests.cpp

Fix getrequests

---

qa/rpc-tests/onboard.py
qa/rpc-tests/onboardmanual.py
src/policy/kycfile.cpp
src/policy/whitelist.cpp
src/qt/addresstablemodel.cpp
src/rpc/blockchain.cpp
src/validation.cpp
src/wallet/rpcdump.cpp
src/wallet/rpcwallet.cpp
src/wallet/wallet.cpp

Title describes all, it is a minor pull request.

Minor changes to onboard tests and a certain key or script id safety check 

---

src/chainparams.cpp
src/chainparamsbase.cpp
src/chainparamsbase.h

- custom params for gold main
- placeholder for terms and conditions

custom gold params

---

src/callrpc.cpp
src/callrpc.h
src/validation.cpp
src/wallet/rpcwallet.cpp

#150 
Plain geth connectivity, no pegin logic yet. Tested with mainchain config, no user/pass is used.

geth connectivity

---

src/policy/kycfile.cpp

Fixed issue (#156) where onboarduser with empty file caused crash

Issue #156 fix

---

qa/pull-tester/rpc-tests.py
qa/rpc-tests/fixedfee.py
src/init.cpp
src/policy/policy.cpp
src/policy/policy.h
src/validation.cpp
src/validation.h
src/wallet/wallet.cpp

If fixedfee is non-zero, then all transactions require exactly fixedtxfee in fees, and wallet generates txs with this fixed fee.

fixed fee option for policy and wallet

---

qa/rpc-tests/bumpfee.py
qa/rpc-tests/confidential_transactions.py
qa/rpc-tests/listtransactions.py
qa/rpc-tests/prioritise_transaction.py
qa/rpc-tests/redemption.py
qa/rpc-tests/splittransactions.py
qa/rpc-tests/test_framework/util.py
qa/rpc-tests/unconfidential_transactions.py
qa/rpc-tests/validBurn.py
qa/rpc-tests/wallet.py
src/rpc/rawtransaction.cpp
src/test/rpc_tests.cpp

No changes necessary to unit tests.
No other unused parameters.

removed unused code and fixed docs

---

qa/rpc-tests/onboard_cit.py
src/policy/kycfile.cpp
src/policy/kycfile.h
src/policy/whitelist.cpp
src/policy/whitelist.h
src/policy/whitelistEncrypted.cpp

Debug onboard kycfile

---

qa/rpc-tests/onboard.py
src/policy/kycfile.cpp
src/policy/kycfile.h
src/wallet/rpcdump.cpp
src/wallet/rpcwallet.cpp

A simple RPC for getting information about a kyc file.

validatekycfile rpc

---

qa/rpc-tests/onboardmanual.py
src/wallet/rpcdump.cpp

createkycfile returns the kycfile string to the terminal instead of writing to a file if the first argument is an empty string ""

Createkycfile output

---

Dockerfile
qa/rpc-tests/onboardmanual.py
src/policy/kycfile.cpp
src/policy/kycfile.h
src/wallet/rpcdump.cpp

Correct validatekycfile iswhietlisted result for mulstisig kycfiles

Correct validatekycfile for multisig wallets

---

qa/rpc-tests/onboard.py
qa/rpc-tests/onboardmanual.py
qa/rpc-tests/onboardmanual_cit.py
src/wallet/rpcdump.cpp
src/wallet/rpcwallet.cpp

Added "vebose" option to validatekycfile rpc

Validatekycfile

---

qa/pull-tester/rpc-tests.py
qa/rpc-tests/blockchain.py
qa/rpc-tests/test_framework/address.py
qa/rpc-tests/wallet.py
src/rpc/blockchain.cpp
src/util.cpp

New branch because of messy merge. 
Can you think of any way to test BLINDED_KEY and SECRET_KEY?

fix getsidechaininfo and add test

---

qa/rpc-tests/sendany.py
src/wallet/rpcwallet.cpp

Allow a change address to be specified for the sendanytoaddress RPC.

sendanytoaddress RPC: optionally specify a change address

---

Dockerfile
configure.ac
contrib/docker/binary-build/Dockerfile
contrib/docker/dpkg-build/Dockerfile
contrib/docker/rpm-build/Dockerfile
src/Makefile.am
src/callrpc.cpp
src/callrpc.h
src/init.cpp

Make curlpp optional (disabled by default)
--with-curlpp=[yes/no]

Optional curlpp
